// Generated by gencpp from file pan_tilt_description/sum.msg
// DO NOT EDIT!


#ifndef PAN_TILT_DESCRIPTION_MESSAGE_SUM_H
#define PAN_TILT_DESCRIPTION_MESSAGE_SUM_H

#include <ros/service_traits.h>


#include <pan_tilt_description/sumRequest.h>
#include <pan_tilt_description/sumResponse.h>


namespace pan_tilt_description
{

struct sum
{

typedef sumRequest Request;
typedef sumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sum
} // namespace pan_tilt_description


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pan_tilt_description::sum > {
  static const char* value()
  {
    return "37cb92532aa956fd8be41d523af9c227";
  }

  static const char* value(const ::pan_tilt_description::sum&) { return value(); }
};

template<>
struct DataType< ::pan_tilt_description::sum > {
  static const char* value()
  {
    return "pan_tilt_description/sum";
  }

  static const char* value(const ::pan_tilt_description::sum&) { return value(); }
};


// service_traits::MD5Sum< ::pan_tilt_description::sumRequest> should match
// service_traits::MD5Sum< ::pan_tilt_description::sum >
template<>
struct MD5Sum< ::pan_tilt_description::sumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pan_tilt_description::sum >::value();
  }
  static const char* value(const ::pan_tilt_description::sumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pan_tilt_description::sumRequest> should match
// service_traits::DataType< ::pan_tilt_description::sum >
template<>
struct DataType< ::pan_tilt_description::sumRequest>
{
  static const char* value()
  {
    return DataType< ::pan_tilt_description::sum >::value();
  }
  static const char* value(const ::pan_tilt_description::sumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pan_tilt_description::sumResponse> should match
// service_traits::MD5Sum< ::pan_tilt_description::sum >
template<>
struct MD5Sum< ::pan_tilt_description::sumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pan_tilt_description::sum >::value();
  }
  static const char* value(const ::pan_tilt_description::sumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pan_tilt_description::sumResponse> should match
// service_traits::DataType< ::pan_tilt_description::sum >
template<>
struct DataType< ::pan_tilt_description::sumResponse>
{
  static const char* value()
  {
    return DataType< ::pan_tilt_description::sum >::value();
  }
  static const char* value(const ::pan_tilt_description::sumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAN_TILT_DESCRIPTION_MESSAGE_SUM_H
