// Generated by gencpp from file pan_tilt_description/sumResponse.msg
// DO NOT EDIT!


#ifndef PAN_TILT_DESCRIPTION_MESSAGE_SUMRESPONSE_H
#define PAN_TILT_DESCRIPTION_MESSAGE_SUMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace pan_tilt_description
{
template <class ContainerAllocator>
struct sumResponse_
{
  typedef sumResponse_<ContainerAllocator> Type;

  sumResponse_()
    : pose_()  {
    }
  sumResponse_(const ContainerAllocator& _alloc)
    : pose_(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose__type;
  _pose__type pose_;





  typedef boost::shared_ptr< ::pan_tilt_description::sumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pan_tilt_description::sumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sumResponse_

typedef ::pan_tilt_description::sumResponse_<std::allocator<void> > sumResponse;

typedef boost::shared_ptr< ::pan_tilt_description::sumResponse > sumResponsePtr;
typedef boost::shared_ptr< ::pan_tilt_description::sumResponse const> sumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pan_tilt_description::sumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pan_tilt_description::sumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pan_tilt_description::sumResponse_<ContainerAllocator1> & lhs, const ::pan_tilt_description::sumResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pose_ == rhs.pose_;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pan_tilt_description::sumResponse_<ContainerAllocator1> & lhs, const ::pan_tilt_description::sumResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pan_tilt_description

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pan_tilt_description::sumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pan_tilt_description::sumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pan_tilt_description::sumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pan_tilt_description::sumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pan_tilt_description::sumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pan_tilt_description::sumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pan_tilt_description::sumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caae3e01e8202bfc17fc4610be0ea329";
  }

  static const char* value(const ::pan_tilt_description::sumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcaae3e01e8202bfcULL;
  static const uint64_t static_value2 = 0x17fc4610be0ea329ULL;
};

template<class ContainerAllocator>
struct DataType< ::pan_tilt_description::sumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pan_tilt_description/sumResponse";
  }

  static const char* value(const ::pan_tilt_description::sumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pan_tilt_description::sumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose_\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pan_tilt_description::sumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pan_tilt_description::sumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pan_tilt_description::sumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pan_tilt_description::sumResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose_: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PAN_TILT_DESCRIPTION_MESSAGE_SUMRESPONSE_H
